# Generated by Django 3.1.2 on 2020-10-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('company_location', models.CharField(default='Ho Chi Minh', max_length=100)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_age', models.IntegerField(default=18)),
                ('join_date', models.DateField(verbose_name='Date Published')),
                ('level', models.CharField(choices=[('BE', 'Beginner'), ('JU', 'Junior'), ('SE', 'Senior'), ('EX', 'Expect'), ('MA', 'Master'), ('GU', 'Guru')], default='BE', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_infor.company')),
            ],
        ),
    ]
